32 hz measure in/out global efficiency av
giovannivolpe/BRAPH-2-Matlab-beta pull request #103
Opened 2023-07-31 13:43 UTC by hanzh346

In and out global efficiency average

2023-08-30 14:54 UTC, bzufiriaki requested changes
I think these files are the same as in the pull request: https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/pull/90. Should not be new files names InGlobalEfficiency**Av**.m and OutGlobalEfficiency**Av**.m ?

2023-08-31 14:15 UTC, bzufiriaki requested changes

2023-08-31 14:15 UTC, bzufiriaki commented on braph2genesis/measures/_InGlobalEfficiency.gen.m
> +known_in_global_efficiency = {[1/4 1/4 1/4 1/4 0]'};
I think this should be: known_in_global_efficiency = {[1/4 1/4 1/4 1/4 0]};

2023-09-03 07:47 UTC, JiaweiSun0512 approved these changes

2023-09-12 07:28 UTC, bzufiriaki approved these changes

2023-09-12 07:50 UTC, merged