Eg 115 random
giovannivolpe/BRAPH-2-Matlab-beta pull request #118
Opened 2023-08-14 10:56 UTC by egolol

2023-08-24 13:02 UTC, giovannivolpe requested changes
1. RANDOMIZATION should not be in the layout (typically queries never are).
2. change "RANDOMIZE ON/OFF" to "RANDOMIZATION ON/OFF" in all in the respective layout titles.
3. Verify with @mitemijalkov that all randomizations are correct that they work. 
4. Add tests for the randomizaiton in all graphs. Also in this case, verify with @mitemijalkov

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_GraphBD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_GraphBU.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_GraphWD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_GraphWU.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultigraphBUD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultigraphBUT.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultilayerBD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultilayerBUD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultilayerWD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexBD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexBU.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexBUD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexBUT.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexWD.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-08-24 13:02 UTC, giovannivolpe commented on braph2genesis/graphs/_MultiplexWU.gen.m
> +RANDOMIZATION VALUE
remove this from layout

2023-09-07 15:40 UTC, bzufiriaki commented
> 3. Verify with @mitemijalkov that all randomizations are correct that they work.   **Verified**
> 4. Add tests for the randomizaiton in all graphs. Also in this case, verify with @mitemijalkov **Added randomization tests for all types of graphs. "

**Still getting error in the randomization tests for MultilayerBUT and MultigraphBUD**

2023-09-08 16:43 UTC, merged