Add MultilayerBU
giovannivolpe/BRAPH-2-Matlab-beta pull request #20
Opened 2023-04-27 10:02 UTC by JiaweiSun0512

1._MultilayerBU.gen.m
2. measures

2023-04-28 14:33 UTC, hanzh346 approved these changes

2023-04-28 20:37 UTC, hanzh346 approved these changes

2023-05-22 15:43 UTC, c-yuwei requested changes

2023-05-22 15:43 UTC, c-yuwei commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +A = B;
Is there particular reason to have this line instread of "value = B;"?

2023-05-22 15:43 UTC, c-yuwei commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +B{3,3} = A3;
leave a space after comma, e.g. 
B12 = rand(size(B1, 1), size(B2, 2));

And spread it across the whole script

2023-05-22 18:30 UTC, egolol approved these changes

2023-06-08 09:05 UTC, annacanal requested changes
All descriptions were wrong, please update them as soon as possible.

2023-06-08 09:05 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +There are connections between layers connecting the corresponding nodes.
In a multilayer binary undirected (BU) graph, layers could have different number 
 of nodes with within-layer undirected edges, associated with either 0 (absence of connection) 
 or 1 (existence of connection).
The connectivity matrices are symmetric (within layer).
All node connections are allowed between layers.

2023-06-08 09:05 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +'In a multilayer binary undirected (BU) graph, layers have same or different nodes with within-layer undirected edges either 0 (absence of connection) or 1 (existence of connection). The connectivity
In a multilayer binary undirected (BU) graph, layers could have different number of nodes with within-layer undirected edges, associated with either 0 (absence of connection) or 1 (existence of connection). The connectivity matrices are symmetric (within layer). All node connections are allowed between layers.

2023-06-08 09:05 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +A (result, cell) is the cell containing the multilayer binary adjacency matrices of the multilayer binary undirected graph.
A (result, cell) is the cell containing the binary supra-adjacency matrix of the multilayer binary undirected graph.

2023-06-08 12:23 UTC, annacanal requested changes

2023-06-08 12:23 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +A (result, cell) is the cell containing the multilayer binary supra-adjacency matrices of the multilayer binary undirected graph.
A (result, cell) is the cell containing the binary supra-adjacency **matrix** of the multilayer binary undirected graph.

2023-06-08 12:24 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBU.gen.m
> +A (result, cell) is the cell containing the multilayer binary supra-adjacency matrices of the multilayer binary undirected graph.
this is still not changed

2023-06-08 13:37 UTC, annacanal approved these changes

2023-06-13 08:07 UTC, bzufiriaki approved these changes

2023-06-17 09:28 UTC, merged