2-bz-OrdMxBUT
giovannivolpe/BRAPH-2-Matlab-beta pull request #21
Opened 2023-04-27 14:29 UTC by bzufiriaki

Added:

- new OrdMxBUT graph

- OrdMxBUT in measures

2023-04-28 07:19 UTC, hanzh346 approved these changes

2023-05-22 12:34 UTC, JiaweiSun0512 approved these changes

2023-06-08 09:21 UTC, annacanal requested changes

2023-06-08 09:21 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUT.gen.m
> +binarized at different thresholds.
In a binary undirected **ordinal** multiplex..

2023-06-08 09:21 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUT.gen.m
> +'In a binary undirected multiplex with fixed thresholds (BUT),  all the layers consist of binary undirected (BU) multiplex graphs  derived from the same weighted supra-connectivity matrices  binarize
In a binary undirected **ordinal** multiplex..

2023-06-08 09:21 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUT.gen.m
> +A (result, cell) is the cell array containing the multiplex binary adjacency matrices of the binary undirected multiplex with fixed thresholds (BUT) and the ordinal connections between layers.
A (result, cell) is the cell array containing the binary supra-adjacency matrix of the binary undirected multiplex with fixed thresholds (BUT).

2023-06-08 10:06 UTC, annacanal approved these changes

2023-06-12 16:47 UTC, merged