2 hz multilayergraphs ord ml wd
giovannivolpe/BRAPH-2-Matlab-beta pull request #22
Opened 2023-04-30 19:45 UTC by hanzh346

Add OrdMultilayer_WD.gen.m and add the graph to distance measure.

Also add OrdMultilayer_WD.gen.m into temp.m for testing

Unitest and GUI are passed.

2023-05-02 08:28 UTC, bzufiriaki approved these changes

2023-05-22 16:07 UTC, c-yuwei requested changes

2023-05-22 16:07 UTC, c-yuwei commented on temp.m
the file should not be updated, according to last discussion in nexus (GV, YC, HZ, EG, AC, BZ)

2023-05-22 16:07 UTC, c-yuwei commented on braph2genesis/graphs/_OrdMlWD.gen.m
> +A = B
leave a space after the comman, e.g. B{3, 2} = A32;
And spread this changes to all the scripts

2023-06-07 19:53 UTC, JiaweiSun0512 approved these changes

2023-06-08 08:57 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWD.gen.m
> +A (result, cell) is the cell containing the multilayer weighted adjacency matrices of the multilayer weighted directed graph.
A (result, cell) is the cell containing the weighted supra-adjacency matrix of the multilayer weighted directed graph.

2023-06-12 09:17 UTC, egolol commented
I can't check it, since i get an error when running braph2genesis. See image: 
![image](https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/assets/15255163/73d39619-61e2-433b-94a1-9423530087f0)

2023-06-12 12:46 UTC, hanzh346 commented
> I can't check it, since i get an error when running braph2genesis. See image: ![image](https://user-images.githubusercontent.com/15255163/245092159-73d39619-61e2-433b-94a1-9423530087f0.png)

Hello Emiliano,

I just tried with it myself, I didnt get the error.

One think you could do is to exclude "braph2" folder from your path before you compile, that raised errors sometimes.

2023-06-12 13:05 UTC, giovannivolpe commented
This is most likely due to the fact that there are still some objects using ConcreteElement in the workspace.
Try to first ensure that the workspace is cleared.

2023-06-12 13:41 UTC, iok-ui approved these changes

2023-06-12 13:43 UTC, c-yuwei commented on temp.m
Remove the changes in this temp.m as discussed before.

2023-06-13 08:06 UTC, bzufiriaki approved these changes

2023-06-13 09:51 UTC, annacanal requested changes

2023-06-13 09:51 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWD.gen.m
> +There are connections between layers connecting the corresponding nodes.
All node connections are allowed between layers.

2023-06-13 09:51 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWD.gen.m
> +'In a multilayer weighted directed (BD) graph, layers could have different number of nodes with within-layer weighted directed edges, associated with a real number between 0 and 1 and indicating the
All node connections are allowed between layers.

2023-06-13 10:05 UTC, hanzh346 commented
this pull request is now merged to another one "2 hz multilayerWU OrdMLWU OrdMxBUD OrdMlWD" https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/pull/9

2023-06-13 10:05 UTC, closed without merging