update
giovannivolpe/BRAPH-2-Matlab-beta pull request #23
Opened 2023-05-09 09:40 UTC by JiaweiSun0512

MultilayerWU (copy from hang)
MultilayerBUD
OrdMlWU 
OrdMlBU
OrdMlBUD
OrdMlBUT

2023-05-22 16:03 UTC, c-yuwei requested changes

2023-05-22 16:03 UTC, iok-ui commented on braph2genesis/graphs/_MultilayerBUD.gen.m
> +% % % 'MultilayerBUD'
do these comment need to be erased?

2023-05-22 16:03 UTC, iok-ui commented on braph2genesis/graphs/_MultilayerBUD.gen.m
> +value = A;
leave a blank line between line 111 and  line 112

2023-05-22 16:03 UTC, iok-ui commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +%% ¡_methods!
why these props are after test? Usually the test is the last session of an element script

2023-05-22 16:03 UTC, iok-ui commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +% A1 = B1;
If the test for Symmetrize, Semipositivize and Standardize Rules, then these comments should be erased

2023-05-22 19:10 UTC, egolol commented
there's a lot of white spaces, other than it's fine.

2023-05-22 19:10 UTC, egolol approved these changes

2023-06-08 08:49 UTC, annacanal requested changes
You need to update your branch and get the new descriptions, and other changes:
https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/pull/9

2023-06-08 08:49 UTC, annacanal commented on braph2genesis/graphs/_OrdMlBUT.gen.m
> +The layers are connected in an ordinal fashion, i.e., only consecutive layers are connected.
this description is wrong, please correct

2023-06-08 08:49 UTC, annacanal commented on braph2genesis/graphs/_OrdMlWU.gen.m
> +The layers are connected in an ordinal fashion, i.e., only consecutive layers are connected.
this description is wrong, please correct based on the updated in this PR: https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/pull/9

2023-06-08 08:49 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +There are connections between layers connecting the corresponding nodes.
you need to update your branch based on this one: https://github.com/giovannivolpe/BRAPH-2-Matlab-beta/pull/9
Descriptions are wrong, you have not updated them

2023-06-08 12:21 UTC, annacanal approved these changes

2023-06-13 08:08 UTC, bzufiriaki approved these changes

2023-06-17 09:28 UTC, merged