2 bz multilayer but
giovannivolpe/BRAPH-2-Matlab-beta pull request #24
Opened 2023-05-17 12:42 UTC by bzufiriaki

Added:

- new MultilayerBUT graph

- MultilayerBUT in measures

2023-06-03 07:01 UTC, hanzh346 commented on braph2genesis/graphs/_MultilayerBUT.gen.m
Should it be supra-adjacency matrix over supra-connectivity matrix on line 7?

2023-06-07 21:08 UTC, JiaweiSun0512 commented on braph2genesis/graphs/_OrdMlWU.gen.m
> +B23 = rand(size(B2,1),size(B3,2));
add space behind Commas

2023-06-08 09:38 UTC, annacanal requested changes

2023-06-08 09:38 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBUT.gen.m
>  MultilayerBUT < MultilayerWU (g, multilayer binary undirected with fixed threaholds graph) is a multilayer binary undirected with fixed threaholds graph.
typo:
MultilayerBUT < MultilayerWU (g, multilayer binary undirected with fixed **thresholds** graph) is a multilayer binary undirected with fixed **thresholds** graph.

2023-06-08 09:38 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBUT.gen.m
>  DESCRIPTION (constant, string) is the description of the multilayer undirected with fixed threaholds graph.
typo: **thresholds**

2023-06-08 09:38 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> +All node connections are allowed between layers.
In a multilayer binary undirected with fixed thresholds (BUT) graph, the layers are those of binary undirected (BU) multiplex graphs derived from the same weighted supra-adjacency matrix binarized at different thresholds. The supra-adjacency matrix has a number of partitions equal to the number of thresholds. Layers 
within the binary undirected (BU) multilayer graphs could have different number of nodes
with within-layer binary undirected edges. Edges can be either 0 (absence of connection)
or 1 (existence of connection).
All node connections are allowed between layers.

2023-06-08 09:38 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> +'In a multilayer binary undirected with fixed thresholds (BUT) graph, layers  consist of binary undirected (BU) multilayer graphs derived from the same weighted supra-connectivity matrices binarized
In a multilayer binary undirected with fixed thresholds (BUT) graph, the layers are those of binary undirected (BU) multiplex graphs derived from the same weighted supra-adjacency matrix binarized at different thresholds. The supra-adjacency matrix has a number of partitions equal to the number of thresholds. Layers 
within the binary undirected (BU) multilayer graphs could have different number of nodes
with within-layer binary undirected edges. Edges can be either 0 (absence of connection)
or 1 (existence of connection).
All node connections are allowed between layers.

2023-06-08 09:38 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> +A (result, cell) is the cell containing the within-layer binary undirected multilayer graphs of the multilayer binary undirected with fixed threaholds graph.
A (result, cell) is the cell array containing the binary supra-adjacency matrix of the multilayer binary undirected with fixed thresholds (BUT) graph.

2023-06-08 09:51 UTC, bzufiriaki reviewed
Updated suggested changes

2023-06-08 10:10 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> +multiplex graphs derived from the same weighted supra-adjacency matrix binarized at different thresholds.
**multilayer** instead of multiplex, sorry I introduced this error before I believe.

2023-06-08 10:10 UTC, annacanal commented on braph2genesis/graphs/_MultilayerBUT.gen.m
> +'In a multilayer binary undirected with fixed thresholds (BUT) graph, the layers are those of binary undirected (BU) multiplex graphs derived from the same weighted supra-adjacency matrix binarized a
**multilayer** instead of multiplex, sorry I introduced this error before I believe.

2023-06-12 15:16 UTC, annacanal approved these changes

2023-06-13 08:02 UTC, JiaweiSun0512 approved these changes

2023-06-15 11:28 UTC, hanzh346 approved these changes

2023-06-16 13:07 UTC, merged