2 bz ord ml bd 2
giovannivolpe/BRAPH-2-Matlab-beta pull request #30
Opened 2023-05-22 11:41 UTC by bzufiriaki

Added:

- new OrdMlBD graph

- modify Distance measure for OrdMlBD

2023-06-03 07:03 UTC, hanzh346 commented on braph2genesis/graphs/_MultilayerWD.gen.m
IN the description, should it be the _all connections are allowed in layers_?

2023-06-08 09:49 UTC, annacanal requested changes

2023-06-08 09:49 UTC, annacanal commented on braph2genesis/graphs/_OrdMlBD.gen.m
> +A (result, cell) is the cell containing the within-layer binary adjacency matrices of the multilayer binary directed graph and the ordinal connections between layers..
you have two final dots (.)

2023-06-08 09:49 UTC, annacanal commented on braph2genesis/graphs/_OrdMlBD.gen.m
> +The layers are connected in an ordinal fashion, i.e., only consecutive layers are connected.
... layers could have different number 
 of nodes with within-layer directed edges. (remove THE before different)

2023-06-08 09:49 UTC, annacanal commented on braph2genesis/graphs/_OrdMlBD.gen.m
> +'In an ordinal multilayer binary directed (BD) graph, layers could have the different number  of nodes with within-layer directed edges. Edges can be either 0 (absence of connection)  or 1 (existence
... layers could have different number 
 of nodes with within-layer directed edges. (remove THE before different)

2023-06-08 10:15 UTC, annacanal approved these changes

2023-06-13 08:09 UTC, JiaweiSun0512 commented on braph2genesis/graphs/_OrdMlBD.gen.m
> +B12 = rand(size(B1,1),size(B2,2));
need space after ','

2023-06-15 11:30 UTC, hanzh346 approved these changes

2023-06-16 13:26 UTC, merged