Eg 32 path length
giovannivolpe/BRAPH-2-Matlab-beta pull request #48
Opened 2023-06-08 15:33 UTC by egolol

2023-06-12 06:27 UTC, hanzh346 approved these changes

2023-06-13 08:09 UTC, JiaweiSun0512 approved these changes

2023-06-13 09:15 UTC, bzufiriaki requested changes

2023-06-13 09:15 UTC, bzufiriaki commented on braph2genesis/measures/_PathLengthAv.gen.m
> +'DegreeAv'
Shouldn´t be "PathLengthAv " instead of "DegreeAv". Same in lines 26, 31, 36, 83

2023-07-04 13:12 UTC, bzufiriaki approved these changes

2023-07-12 12:08 UTC, merged