Update Authors
giovannivolpe/BRAPH-2-Matlab-beta pull request #6
Opened 2023-03-31 03:22 UTC by giovannivolpe

2023-03-31 03:27 UTC, giovannivolpe commented
@hanzh346 @bzufiriaki @JiaweiSun0512 please check the changes with your author information.

@hanzh346 @JiaweiSun0512 please add your ORCID (if you don't have one, create it).

2023-05-02 07:28 UTC, bzufiriaki requested changes

2023-05-02 07:28 UTC, bzufiriaki commented on CITATION.cff
> +    email: blanca.zufiria@ki.se
email: blanca.zufiria.gerboles@ki.se

2023-05-03 18:10 UTC, giovannivolpe commented on CITATION.cff
> +    email: blanca.zufiria@ki.se
changed email

2023-05-15 14:39 UTC, JiaweiSun0512 commented on .zenodo.json
> +            "orcid": "",
0000-0002-2986-2734

2023-05-15 14:40 UTC, JiaweiSun0512 commented on CITATION.cff
> +    orcid: 'https://orcid.org/'
https://orcid.org/0000-0002-2986-2734

2023-05-15 14:48 UTC, merged