Update surface references
giovannivolpe/BRAPH-2-Matlab-beta pull request #73
Opened 2023-06-30 11:16 UTC by egolol

2023-06-30 12:53 UTC, iok-ui commented on tutorials/general/tut_ba/tut_ba.tex
> -	{\includegraphics{tut_ba/fig10.png}}
There is an issue with compiling "tut_ba.tex" file due to the mismatch in relative path of PNG files. Previously, this "tut_ba.tex" was located in the "tutorials/general" path, resulting in the relative paths like "tut_ba/fig10.png". However, after moving the "tut_ba.tex" file to "tutorials/general/tut_ba", the relative paths no longer match. 

To resolve this, two possible solutions might be considered:
1. Revise all the relative path of the PNG files from "/tut_ba/fig10.png" to just "fig10.png", or 
2. Create a folder named "figures" and change the relative path of png files to "/figures/fig10.png". 

By doing this, it can establish a consistent path structure for the PNG files.

2023-06-30 16:05 UTC, c-yuwei approved these changes

2023-06-30 17:53 UTC, giovannivolpe requested changes
Please, make the same changes also in the tutorials/general/tut_ba/readme.md file, after @Joana70 has approved it

2023-07-03 15:24 UTC, Joana70 requested changes
Hi Emiliano,
Can you add the references for the human brain atlases. Most of them were from BrainNet Viewer so you can check the paper they published. One of them I think it was Mite who found it. Ask Mite.

2023-09-29 08:05 UTC, closed without merging