2 hz multilayergraphs
giovannivolpe/BRAPH-2-Matlab-beta pull request #9
Opened 2023-04-06 19:59 UTC by hanzh346

OrdMxBUD.gen.m created, unitest passed
Closes #2

2023-05-02 07:20 UTC, bzufiriaki approved these changes

2023-05-22 11:24 UTC, annacanal requested changes
Descriptions need to be modified in the 3 graphs implemented in this pull request, see my recommendations in each comment

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +There are connections between layers connecting the corresponding nodes.
I would substitute these two sentences by:
**The connectivity matrices are symmetric (within layer).
All node connections are allowed between layers.**

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +'In a multilayer weighted undirected (WU) graph, layers could have different number of nodes with within-layer weighted undirected edges, associated with a real number between 0 and 1 and indicating
update here the description based on the previous comment

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_OrdMlWU.gen.m
> +The layers are connected in an ordinal fashion.
I would substitute these three sentences by:
**The connectivity matrices are symmetric (within layer).
All node connections are allowed between layers.
The layers are connected in an ordinal fashion, i.e., only consecutive layers are connected.**

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_OrdMlWU.gen.m
> +
update the description

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_OrdMlWU.gen.m
> +A (result, cell) is the cell containing the multilayer weighted adjacency matrices of the multilayer weighted undirected graph.
it contains more than adjacency matrices. So either you say that it contains the **multilayer weighted supra-adjacency matrix** or you say that it contains the within-layer weighted adjacency matrices of the multilayer weighted undirected graph and the ordinal connections between layers.

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +A (result, cell) is the cell containing the multilayer weighted adjacency matrices of the multilayer weighted undirected graph.
it contains more than adjacency matrices. So either you say that it contains the multilayer weighted supra-adjacency matrix or you say that it contains the within-layer weighted adjacency matrices of the multilayer weighted undirected graph and the connections between layers.

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUD.gen.m
> +The layers are connected in an ordinal fashion, i.e., only consecutive layers are connected.
There is just **one supra-adjacency matrix** in the weighted multiplex/multilayer, if you talk in plural you mean the within-layer connectivity matrix. Also talk about the supra-adjacency matrix, not the supra connectivity matrix.

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUD.gen.m
> +The layers are connected in an ordinal fashion, i.e., only consecutive layers are connected.
Also: In an ordinal... ; this needs to be rewritten.

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUD.gen.m
> +
update

2023-05-22 11:24 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUD.gen.m
> +A (result, cell) is the cell array containing the multiplex binary adjacency matrices of the binary undirected multiplex.
is the cell array containing the multiplex binary **supra**-adjacency matrices of the binary undirected multiplex

2023-05-22 12:29 UTC, JiaweiSun0512 approved these changes

2023-05-22 15:52 UTC, c-yuwei requested changes

2023-05-22 15:52 UTC, c-yuwei commented on temp.m
This file should not be updated, according to last discussion

2023-05-22 15:52 UTC, c-yuwei commented on braph2genesis/measures/_Distance.gen.m
> +B12 = rand(size(B11,1),size(B22,2));
Leave a space after comman, i.e. 
"B12 = rand(size(B11, 1), size(B22, 2));"
And distribute the changes across the script and keep the style consistent

2023-06-08 08:54 UTC, annacanal commented on braph2genesis/graphs/_MultilayerWU.gen.m
> +A (result, cell) is the cell containing the multilayer weighted supra-adjacency matrices of the multilayer weighted undirected graph.
A (result, cell) is the cell containing the multilayer weighted supra-adjacency matrix.

2023-06-13 06:44 UTC, c-yuwei requested changes
Overall it is good. Two things before merging:

1.  there should not be any changes for the temp.m file
2. there are conflicts in the measures (Degree, DegreeAv, Distance). From first glance, it seems due to OrdMxBUT implemnted in the develop. This changes of OrdMxBUT needs to be coped with into this PR

2023-06-13 07:53 UTC, annacanal approved these changes

2023-06-13 07:53 UTC, annacanal commented on braph2genesis/graphs/_OrdMxBUD.gen.m
> +A (result, cell) is the cell array containing the multiplex binary supra-adjacency matrices of the binary undirected multiplex.
A (result, cell) is the cell array containing the binary supra-adjacency matrix of the binary undirected multiplex.

2023-06-13 08:00 UTC, c-yuwei approved these changes

2023-06-15 12:45 UTC, egolol approved these changes

2023-06-15 15:57 UTC, merged